apiVersion: v1
kind: Service
metadata:
  name: hmpps-court-cases-release-dates-design-service
spec:
  selector:
    app: hmpps-court-cases-release-dates-design # this should match the pod label in deployment.yml
  ports:
    - name: https
      port: 8080
      targetPort: 8080
