name: Deprecate Node.js package

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: 'https://registry.npmjs.org'
        env:
          version: ${{ github.event.release.tag_name }}
      - run: npm deprecate hmpps-design-system-frontend "Name has changed, use hmpps-court-cases-release-dates-design package instead"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
